DEBUG = True
RESTAURANT_CATEGORIES = [
    {"k":"afghani", "v":"Afghan"},
    {"k":"african", "v":"African"},
    {"k":"newamerican", "v":"American (New)"},
    {"k":"tradamerican", "v":"American (Traditional)"},
    {"k":"arabian", "v":"Arabian"},
    {"k":"argentine", "v":"Argentine"},
    {"k":"armenian", "v":"Armenian"},
    {"k":"australian", "v":"Australian"},
    {"k":"bangladeshi", "v":"Bangladeshi"},
    {"k":"bbq", "v":"Barbeque"},
    {"k":"basque", "v":"Basque"},
    {"k":"belgian", "v":"Belgian"},
    {"k":"brasseries", "v":"Brasseries"},
    {"k":"brazilian", "v":"Brazilian"},
    {"k":"breakfast_brunch", "v":"Breakfast & Brunch"},
    {"k":"british", "v":"British"},
    {"k":"buffets", "v":"Buffets"},
    {"k":"bulgarian", "v":"Bulgarian"},
    {"k":"burgers", "v":"Burgers"},
    {"k":"burmese", "v":"Burmese"},
    {"k":"cafes", "v":"Cafes"},
    {"k":"cafeteria", "v":"Cafeteria"},
    {"k":"cajun", "v":"Cajun/Creole"},
    {"k":"cambodian", "v":"Cambodian"},
    {"k":"caribbean", "v":"Caribbean"},
    {"k":"chinese", "v":"Chinese"},
    {"k":"colombian", "v":"Colombian"},
    {"k":"comfortfood", "v":"Comfort Food"},
    {"k":"cuban", "v":"Cuban"},
    {"k":"diners", "v":"Diners"},
    {"k":"egyptian", "v":"Egyptian"},
    {"k":"ethiopian", "v":"Ethiopian"},
    {"k":"hotdogs", "v":"Fast Food"},
    {"k":"filipino", "v":"Filipino"},
    {"k":"french", "v":"French"},
    {"k":"german", "v":"German"},
    {"k":"greek", "v":"Greek"},
    {"k":"hungarian", "v":"Hungarian"},
    {"k":"indpak", "v":"Indian"},
    {"k":"indonesian", "v":"Indonesian"},
    {"k":"irish", "v":"Irish"},
    {"k":"italian", "v":"Italian"},
    {"k":"japanese", "v":"Japanese"},
    {"k":"korean", "v":"Korean"},
    {"k":"kosher", "v":"Kosher"},
    {"k":"lebanese", "v":"Lebanese"},
    {"k":"malaysian", "v":"Malaysian"},
    {"k":"mediterranean", "v":"Mediterranean"},
    {"k":"mexican", "v":"Mexican"},
    {"k":"persian", "v":"Persian/Iranian"},
    {"k":"peruvian", "v":"Peruvian"},
    {"k":"pizza", "v":"Pizza"},
    {"k":"polish", "v":"Polish"},
    {"k":"puertorican", "v":"Puerto Rican"},
    {"k":"russian", "v":"Russian"},
    {"k":"salad", "v":"Salad"},
    {"k":"sandwiches", "v":"Sandwiches"},
    {"k":"scandinavian", "v":"Scandinavian"},
    {"k":"seafood", "v":"Seafood"},
    {"k":"singaporean", "v":"Singaporean"},
    {"k":"slovakian", "v":"Slovakian"},
    {"k":"soulfood", "v":"Soul Food"},
    {"k":"southern", "v":"Southern"},
    {"k":"spanish", "v":"Spanish"},
    {"k":"syrian", "v":"Syrian"},
    {"k":"thai", "v":"Thai"},
    {"k":"turkish", "v":"Turkish"},
    {"k":"uzbek", "v":"Uzbek"},
    {"k":"vegan", "v":"Vegan"},
    {"k":"vegetarian", "v":"Vegetarian"},
    {"k":"vietnamese", "v":"Vietnamese"}]
