DEBUG = True
RESTAURANT_CATEGORIES = [
    {"afghani":"Afghan"},
    {"african":"African"},
    {"newamerican":"American (New)"},
    {"tradamerican":"American (Traditional)"},
    {"arabian":"Arabian"},
    {"argentine":"Argentine"},
    {"armenian":"Armenian"},
    {"australian":"Australian"},
    {"bangladeshi":"Bangladeshi"},
    {"bbq":"Barbeque"},
    {"basque":"Basque"},
    {"belgian":"Belgian"},
    {"brasseries":"Brasseries"},
    {"brazilian":"Brazilian"},
    {"breakfast_brunch":"Breakfast & Brunch"},
    {"british":"British"},
    {"buffets":"Buffets"},
    {"bulgarian":"Bulgarian"},
    {"burgers":"Burgers"},
    {"burmese":"Burmese"},
    {"cafes":"Cafes"},
    {"cafeteria":"Cafeteria"},
    {"cajun":"Cajun/Creole"},
    {"cambodian":"Cambodian"},
    {"caribbean":"Caribbean"},
    {"chinese":"Chinese"},
    {"colombian":"Colombian"},
    {"comfortfood":"Comfort Food"},
    {"cuban":"Cuban"},
    {"diners":"Diners"},
    {"egyptian":"Egyptian"},
    {"ethiopian":"Ethiopian"},
    {"hotdogs":"Fast Food"},
    {"filipino":"Filipino"},
    {"french":"French"},
    {"german":"German"},
    {"greek":"Greek"},
    {"hungarian":"Hungarian"},
    {"indpak":"Indian"},
    {"indonesian":"Indonesian"},
    {"irish":"Irish"},
    {"italian":"Italian"},
    {"japanese":"Japanese"},
    {"korean":"Korean"},
    {"kosher":"Kosher"},
    {"lebanese":"Lebanese"},
    {"malaysian":"Malaysian"},
    {"mediterranean":"Mediterranean"},
    {"mexican":"Mexican"},
    {"persian":"Persian/Iranian"},
    {"peruvian":"Peruvian"},
    {"pizza":"Pizza"},
    {"polish":"Polish"},
    {"puertorican":"Puerto Rican"},
    {"russian":"Russian"},
    {"salad":"Salad"},
    {"sandwiches":"Sandwiches"},
    {"scandinavian":"Scandinavian"},
    {"seafood":"Seafood"},
    {"singaporean":"Singaporean"},
    {"slovakian":"Slovakian"},
    {"soulfood":"Soul Food"},
    {"southern":"Southern"},
    {"spanish":"Spanish"},
    {"syrian":"Syrian"},
    {"thai":"Thai"},
    {"turkish":"Turkish"},
    {"uzbek":"Uzbek"},
    {"vegan":"Vegan"},
    {"vegetarian":"Vegetarian"},
    {"vietnamese":"Vietnamese"}]
